apiVersion: v1
kind: Service
metadata:
  labels:
    app: dnsserver
  name: dnsserver-service
spec:
  ports:
  - port: 80
  selector:
    app: dnsserver
    component: nginx-server
  type: LoadBalancer
  loadBalancerIP: 104.196.113.89
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dnsserver
  name: dnsserver-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dnsserver
        component: nginx-server
    spec:
      containers:
      - name: dnsserver
        image: gcr.io/ieisite-163707/dnsserver:v30
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: "128Mi"
