apiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  labels:
    app: portal
  name: portal-web-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: portal
    component: web-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{namespace}}
  labels:
    app: portal
  name: portal-web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portal
        component: web-server
    spec:
      containers:
      - name: portal
        image: gcr.io/ieisite-163707/portal: #vX.Y.Z  - Make sure to specify the right image version here in DEPLOY file!
        ports:
        - containerPort: 3000
        env: 
        - name: ENV_NAME
          value: {{namespace}}
        resources:
          limits:
            cpu: 50m
            memory: "128Mi"