apiVersion: v1
kind: Service
metadata:
  labels:
    app: website
  name: website-web-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: website
    component: web-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: website
  name: website-web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website
        component: web-server
    spec:
      containers:
      - name: website
        # Make sure to specify the right image version here!
        image: gcr.io/ieisite-163707/website:v39
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 50m
            memory: "128Mi"